### ISSUE TITLE
SEAL only works correctly in the C:/ drive

### ISSUE THREAD

**Issue by Zeale** [SirEatsALotOff/SEAL#10]
I know you told me that this is how this works and I'm pretty sure that you've informed your users in each update, but this is an issue. :P

**Comment by SirEatsALotOff** [comment]
not really... the shortcuts have to exist anyways for it to work...

**Comment by SirEatsALotOff** [comment]
ya know, hillarious thing is that I've accidentally fixed this problem in the past with one of my batch files...

**Comment by Zeale** [comment]
Ok... then should I add a new issue for you to remove the optional install location from the installer? There's something wrong here, and if this is not it then the installer is.

**Comment by Zeale** [comment]
I know what your response is gonna be; I'm just making a point.

**Comment by Zeale** [comment]
:P
