### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by Zeale** [SirEatsALotOff/SEAL#6]
Batch commands can be injected into variables, resulting in errors. For instance, in the main input area, where you give the program your "command," users can type "goto help" and the program will crash.

**Comment by Zeale** [comment]
`wontfix`? Just wrap crap in quotes...

**Comment by SirEatsALotOff** [comment]
wrap which crap in quotes, I'm too lazy to find out, even though I already know.

**Comment by Zeale** [comment]
The thing

**Comment by Zeale** [comment]
DID YOU DO IT YE-

**Comment by Zeale** [comment]
I like how I can close this issue EVEN THOUGH I CAN'T ADD LABE-

**Comment by Zeale** [comment]
But seriously, I don't know (even though I do). Just add them to the right place. I've gotta go work on my own repository and be depressed.

**Comment by SirEatsALotOff** [comment]
I'm not going to fix mine, very few commands would actually need it

**Comment by Zeale** [comment]
Ok then...
